const DISPLAY_LABELS: Record<string, string> = {
  Album: "专辑",
  EP: "迷你专辑（EP）",
  Mixtape: "混音带",
  Soundtrack: "电影原声",
  "Abstract Hip Hop": "抽象嘻哈",
  "Alternative R&B": "另类节奏布鲁斯",
  Ambient: "氛围音乐",
  "Ambient Pop": "氛围流行",
  "Art Pop": "艺术流行",
  "Chamber Music": "室内乐",
  "Chamber Pop": "室内流行",
  "Dark Jazz": "黑暗爵士",
  Downtempo: "缓拍",
  "Dream Pop": "梦幻流行",
  Electronic: "电子",
  "Folk Pop": "民谣流行",
  "Glitch Pop": "故障流行",
  "Indie Folk": "独立民谣",
  "Indie Rock": "独立摇滚",
  Indietronica: "独立电子",
  "Jazz Rap": "爵士说唱",
  "Musique concrète": "具体音乐",
  "Neo-Psychedelia": "新迷幻",
  "Neo-Soul": "新灵魂乐",
  "Post-Rock": "后摇滚",
  "Psychedelic Pop": "迷幻流行",
  "Singer-Songwriter": "唱作人",
  Slowcore: "慢核",
  Synthpop: "合成器流行",
  acoustic: "原声",
  cinematic: "电影感",
  collaborative: "合作",
  colorful: "多彩",
  futuristic: "未来感",
  gentle: "温柔",
  introspective: "内省",
  "late night": "深夜",
  lush: "丰润",
  melancholic: "忧郁",
  nocturnal: "夜晚",
  oceanic: "海洋感",
  playful: "俏皮",
  reflective: "沉思",
  summer: "夏日",
  urban: "都市",
  warm: "温暖",
};

export function getDisplayLabel(sourceLabel: string) {
  return DISPLAY_LABELS[sourceLabel] ?? sourceLabel;
}
