const seed = (
  slug,
  artist,
  title,
  coreGenres,
  relatedGenres = [],
  descriptors = [],
  contexts = [],
  albumId = null,
  sourceMarketChannels = [],
  guide = null,
) => ({
  slug,
  query: { artist, title },
  albumId,
  coreGenres,
  relatedGenres,
  descriptors,
  contexts,
  sourceMarketChannels,
  guide,
});

const guide = (summaryZh, whyListenZh) => ({
  summaryZh,
  whyListenZh,
  confidence: "curated",
  humanReviewed: true,
});

export const NETEASE_CATALOG_SEEDS = [
  seed("wake-after-the-rain", "艾志恒Asen", "在雨后醒来", ["hip-hop"], ["alternative-rnb"], ["introspective", "melodic", "urban"], ["夜晚", "独处"], "287974232", [], guide("旋律说唱与内省叙事贯穿整张作品，情绪从雨后的迟疑逐渐转向清醒。", "适合在夜晚按曲序完整聆听，留意旋律、人声层次与叙事推进。")),
  seed("super-mr-sun", "SASIOVERLXRD", "超级孙先生", ["hip-hop"], ["experimental-hip-hop"], ["raw", "playful", "dense"], ["夜晚", "反复聆听"], "286248593", [], guide("锋利的语言、跳脱结构与地下说唱质感组成一张个性鲜明的长篇作品。", "适合关注押韵、采样与段落切换，在重复聆听中发现细节。")),
  seed("fantasy-jay-chou", "周杰伦", "范特西", ["pop"], ["alternative-rnb", "hip-hop"], ["melodic", "nostalgic", "layered"], ["通勤", "周末"], "18915", [], guide("R&B、说唱与华语旋律在多样编曲中保持统一。", "从熟悉旋律进入，留意节拍、人声层次和曲目之间的风格切换。")),
  seed("ye-hui-mei", "周杰伦", "叶惠美", ["pop"], ["alternative-rnb", "hip-hop"], ["cinematic", "melodic", "dramatic"], ["通勤", "夜晚"]),
  seed("black-tangerine", "陶喆", "黑色柳丁", ["pop"], ["alternative-rnb", "rock"], ["groovy", "dramatic", "urban"], ["通勤", "周末"]),
  seed("the-great-leap", "陶喆", "太平盛世", ["pop"], ["alternative-rnb"], ["layered", "groovy", "reflective"], ["通勤", "专注聆听"]),
  seed("fuzao", "王菲", "浮躁", ["experimental-pop"], ["dream-pop", "alternative-rock"], ["airy", "playful", "abstract"], ["独处", "夜晚"], "29748", [], guide("自由的人声与轻盈编曲让整张作品在流行结构之外保持跳脱。", "适合按顺序进入，关注人声、节奏与留白之间不断变化的关系。")),
  seed("fable", "王菲", "寓言", ["pop"], ["dream-pop", "experimental-pop"], ["ethereal", "cinematic", "introspective"], ["夜晚", "独处"]),
  seed("u87", "陈奕迅", "U87", ["pop"], ["alternative-rock"], ["melodic", "urban", "reflective"], ["通勤", "夜晚"], "6491"),
  seed("red-leslie", "张国荣", "红", ["pop"], ["dream-pop", "electronic"], ["sensual", "dramatic", "nocturnal"], ["夜晚", "独处"], "19038"),
  seed("ru-ye", "陈粒", "如也", ["folk"], ["singer-songwriter"], ["intimate", "poetic", "acoustic"], ["独处", "清晨"], "3098832"),
  seed("shan-he-shui", "窦唯", "山河水", ["electronic"], ["experimental-rock", "ambient"], ["abstract", "meditative", "spacious"], ["专注聆听", "夜晚"]),
  seed("black-dream", "窦唯", "黑梦", ["rock"], ["alternative-rock", "post-punk"], ["dark", "tense", "atmospheric"], ["夜晚", "独处"], "7608", [], guide("低沉声线、吉他与合成器共同营造幽暗而紧绷的连续气氛。", "适合夜间整张播放，关注节奏与音色如何持续塑造空间。")),
  seed("rock-n-roll-on-the-new-long-march", "崔健", "新长征路上的摇滚", ["rock"], ["folk-rock"], ["raw", "direct", "rhythmic"], ["通勤", "专注聆听"], "6311"),
  seed("omnipotent-youth-society", "万能青年旅店", "万能青年旅店 同名专辑", ["rock"], ["indie-rock", "art-rock"], ["narrative", "dynamic", "urban"], ["专注聆听", "夜晚"]),
  seed("inside-the-cable-temple", "万能青年旅店", "冀西南林路行", ["rock"], ["art-rock", "progressive-rock"], ["narrative", "cinematic", "dynamic"], ["专注聆听", "独处"], "120605500", [], guide("长篇编曲、铜管和器乐呼应把地域经验转化为连续叙事。", "适合留出完整时间，顺着段落转换与器乐主题进入作品。")),
  seed("the-clod", "草东没有派对", "瓦合", ["rock"], ["indie-rock", "post-punk"], ["tense", "raw", "melancholic"], ["夜晚", "通勤"], "162870766"),
  seed("the-servile", "草东没有派对", "丑奴儿", ["rock"], ["indie-rock", "post-punk"], ["raw", "melancholic", "explosive"], ["夜晚", "独处"]),
  seed("cassa-nova", "落日飛車 Sunset Rollercoaster", "Cassa Nova", ["dream-pop"], ["indie-pop", "psychedelic-pop"], ["dreamy", "warm", "groovy"], ["夜晚", "放松"]),
  seed("bathroom", "deca joins", "浴室", ["indie-rock"], ["dream-pop"], ["intimate", "hazy", "melancholic"], ["夜晚", "独处"]),
  seed("zero-point-seven", "惘闻", "0.7", ["post-rock"], ["instrumental-rock"], ["cinematic", "expansive", "gradual"], ["专注聆听", "夜晚"]),
  seed("rainbow-mountain", "文雀", "彩虹山", ["post-rock"], ["instrumental-rock"], ["bright", "expansive", "gradual"], ["工作", "专注聆听"]),
  seed("the-most-wonderful-journey", "声音玩具", "最美妙的旅行", ["rock"], ["indie-rock", "art-rock"], ["poetic", "dynamic", "reflective"], ["专注聆听", "通勤"]),
  seed("jelly-empire", "木马", "果冻帝国", ["rock"], ["alternative-rock", "post-punk"], ["dark", "dramatic", "urban"], ["夜晚", "独处"]),
  seed("arthropods", "33EMYBW", "Arthropods", ["electronic"], ["experimental-electronic"], ["polyrhythmic", "abstract", "futuristic"], ["专注聆听", "工作"]),
  seed("birdy-island-remixes", "Howie Lee", "鸟岛(Remixes)", ["electronic"], ["experimental-electronic", "ambient"], ["textural", "futuristic", "spacious"], ["夜晚", "专注聆听"], "135678901"),
  seed("entertainment-world", "林强", "娱乐世界", ["electronic"], ["experimental-pop"], ["digital", "playful", "urban"], ["夜晚", "通勤"]),
  seed("temple-fair-tour", "左小祖咒", "庙会之旅", ["experimental-rock"], ["art-rock"], ["theatrical", "raw", "satirical"], ["专注聆听", "独处"]),
  seed("jims-restaurant", "赵雷", "吉姆餐厅", ["folk"], ["singer-songwriter"], ["intimate", "narrative", "warm"], ["夜晚", "独处"]),
  seed("everything-is-not-as-bad", "万晓利", "这一切没有想象的那么糟", ["folk"], ["singer-songwriter"], ["reflective", "acoustic", "narrative"], ["独处", "清晨"]),
  seed("virtuous", "苏阳", "贤良", ["folk"], ["folk-rock"], ["earthy", "narrative", "rhythmic"], ["通勤", "周末"]),
  seed("black-cab", "Higher Brothers", "Black Cab", ["hip-hop"], ["trap"], ["energetic", "urban", "playful"], ["通勤", "运动"]),
  seed("dark-horse", "马思唯", "黑马", ["hip-hop"], ["trap"], ["confident", "melodic", "urban"], ["通勤", "运动"]),
  seed("science-fiction", "法老", "科幻小说", ["hip-hop"], ["alternative-hip-hop"], ["narrative", "dense", "cinematic"], ["专注聆听", "夜晚"]),
  seed("key-to-l", "KEY.L刘聪", "KEY to L", ["hip-hop"], ["alternative-hip-hop"], ["reflective", "urban", "melodic"], ["通勤", "夜晚"]),
  seed("air-plan", "艾热 AIR", "AIR PLAN", ["hip-hop"], ["alternative-rnb"], ["melodic", "warm", "groovy"], ["通勤", "周末"]),
  seed("song-of-the-mountain", "刀郎", "山歌寥哉", ["folk"], ["folk-pop"], ["narrative", "traditional", "dramatic"], ["专注聆听", "周末"], "169512732"),
  seed("window-side-wish", "吴宇深", "窗边盼望", [], [], [], [], "386884453", ["ALL", "ZH"]),
  seed("wind-on-the-mountain", "巴扎黑", "吹吹山顶的风", [], [], [], [], "387217523", ["ALL", "ZH"]),
  seed("that-glance", "王赛罕娜", "那一眼", [], [], [], [], "386378826", ["ALL", "ZH"]),
  seed("poem-to-the-heartless", "云汐", "诗敬薄情人", [], [], [], [], "386877428", ["ZH"]),
  seed("graduating-from-a-chapter", "阿力普", "毕业生 GRADUATING FROM A CHAPTER OF LIFE", [], [], [], [], "386849800", ["ZH"]),
  seed("topic-six-decennium", "体熊专科", "Topic 6: 拾 Decennium", [], [], [], [], "384653629", ["ZH"]),
  seed("upward-spiral", "KKECHO", "Upward Spiral (扶瑶直上)", ["hip-hop"], ["trap"], ["energetic"], ["运动"], "386632533", ["ZH"]),
  seed("from-sand-to-wave", "Mikann耙耙柑", "从沙至浪", ["hip-hop"], ["alternative-hip-hop"], ["urban"], ["通勤"], "387010610", ["ZH"]),
  seed("mysterious-path", "拗拗 NeoNew", "Mysterious Path", ["electronic"], ["experimental-electronic"], ["futuristic"], ["夜晚"], "386815599", ["ZH"]),
  seed("rumours", "Fleetwood Mac", "Rumours", ["rock"], ["soft-rock", "pop-rock"], ["melodic", "warm", "bittersweet"], ["通勤", "周末"], "1637054"),
  seed("blue-joni-mitchell", "Joni Mitchell", "Blue", ["folk"], ["singer-songwriter"], ["intimate", "reflective", "acoustic"], ["独处", "夜晚"], "1724200"),
  seed("beyonce", "Beyoncé", "BEYONCÉ", ["pop"], ["alternative-rnb"], ["confident", "sensual", "cinematic"], ["夜晚", "运动"], "2732013"),
  seed("hit-me-hard-and-soft", "Billie Eilish", "HIT ME HARD AND SOFT", ["pop"], ["alternative-pop"], ["intimate", "dynamic", "dark"], ["夜晚", "独处"], "195498828"),
  seed("first-love", "宇多田ヒカル", "First Love", ["pop"], ["alternative-rnb"], ["melodic", "intimate", "nostalgic"], ["夜晚", "通勤"], "2093862"),
  seed("12-ryuichi-sakamoto", "坂本龍一", "12", ["ambient"], ["modern-classical"], ["meditative", "minimal", "intimate"], ["专注聆听", "独处"], "158396696"),
  seed("map-of-the-soul-7", "BTS (防弹少年团)", "MAP OF THE SOUL : 7", ["pop"], ["hip-hop"], ["dramatic", "energetic", "melodic"], ["运动", "通勤"], "85783683"),
  seed("palette-iu", "IU", "Palette", ["pop"], ["alternative-rnb"], ["warm", "melodic", "reflective"], ["通勤", "周末"], "35377328"),
  seed("ok-computer", "Radiohead", "OK Computer", ["alternative-rock"], ["art-rock"], ["alienated", "cinematic", "dynamic"], ["专注聆听", "夜晚"]),
  seed("hounds-of-love", "Kate Bush", "Hounds of Love", ["art-pop"], ["experimental-pop"], ["cinematic", "dramatic", "layered"], ["专注聆听", "夜晚"]),
  seed("loveless", "My Bloody Valentine", "Loveless", ["dream-pop"], ["shoegaze"], ["hazy", "dense", "immersive"], ["夜晚", "专注聆听"]),
  seed("souvlaki", "Slowdive", "Souvlaki", ["dream-pop"], ["shoegaze"], ["dreamy", "melancholic", "spacious"], ["夜晚", "独处"]),
  seed("to-pimp-a-butterfly", "Kendrick Lamar", "To Pimp a Butterfly", ["hip-hop"], ["experimental-hip-hop", "jazz-rap"], ["narrative", "dense", "groovy"], ["专注聆听", "阅读歌词"]),
  seed("madvillainy", "Madvillain", "Madvillainy", ["hip-hop"], ["experimental-hip-hop"], ["playful", "dense", "sample-based"], ["通勤", "反复聆听"]),
  seed("discovery-daft-punk", "Daft Punk", "Discovery", ["electronic"], ["house", "synth-pop"], ["bright", "groovy", "futuristic"], ["运动", "通勤"]),
  seed("untrue", "Burial", "Untrue", ["electronic"], ["uk-garage", "ambient"], ["nocturnal", "spacious", "melancholic"], ["夜晚", "独处"]),
  seed("kind-of-blue", "Miles Davis", "Kind of Blue", ["jazz"], ["modal-jazz"], ["spacious", "improvised", "calm"], ["晚餐", "专注聆听"]),
  seed("a-love-supreme", "John Coltrane", "A Love Supreme", ["jazz"], ["spiritual-jazz"], ["intense", "meditative", "cohesive"], ["专注聆听", "独处"]),
  seed("heaven-or-las-vegas", "Cocteau Twins", "Heaven or Las Vegas", ["dream-pop"], ["ethereal-wave"], ["ethereal", "bright", "immersive"], ["夜晚", "放松"]),
  seed("agaetis-byrjun", "Sigur Rós", "Ágætis byrjun", ["post-rock"], ["ambient"], ["expansive", "gradual", "bright"], ["专注聆听", "放松"]),
  seed("lift-your-skinny-fists", "Godspeed You! Black Emperor", "Lift Your Skinny Fists Like Antennas to Heaven", ["post-rock"], ["experimental-rock"], ["cinematic", "gradual", "intense"], ["专注聆听", "深夜"]),
  seed("master-of-puppets", "Metallica", "Master of Puppets", ["metal"], ["thrash-metal"], ["fast", "precise", "intense"], ["运动", "专注聆听"]),
];

export const REQUIRED_NETEASE_SAMPLES = [
  { albumId: "287974232", title: "在雨后醒来", artist: "艾志恒Asen" },
  { albumId: "286248593", title: "超级孙先生", artist: "SASIOVERLXRD" },
];
