const entry = (key, labelZh, labelEn, kind) => ({ key, labelZh, labelEn, kind });

export const CATALOG_TAXONOMY = [
  entry("pop", "流行", "Pop", "core"),
  entry("rock", "摇滚", "Rock", "core"),
  entry("hip-hop", "嘻哈", "Hip Hop", "core"),
  entry("electronic", "电子", "Electronic", "core"),
  entry("folk", "民谣", "Folk", "core"),
  entry("experimental-pop", "实验流行", "Experimental Pop", "core"),
  entry("experimental-rock", "实验摇滚", "Experimental Rock", "core"),
  entry("alternative-rock", "另类摇滚", "Alternative Rock", "core"),
  entry("indie-rock", "独立摇滚", "Indie Rock", "core"),
  entry("dream-pop", "梦幻流行", "Dream Pop", "core"),
  entry("post-rock", "后摇滚", "Post-Rock", "core"),
  entry("ambient", "氛围音乐", "Ambient", "core"),
  entry("art-pop", "艺术流行", "Art Pop", "core"),
  entry("jazz", "爵士", "Jazz", "core"),
  entry("metal", "金属", "Metal", "core"),
  entry("alternative-rnb", "另类 R&B", "Alternative R&B", "related"),
  entry("experimental-hip-hop", "实验嘻哈", "Experimental Hip Hop", "related"),
  entry("alternative-hip-hop", "另类嘻哈", "Alternative Hip Hop", "related"),
  entry("alternative-pop", "另类流行", "Alternative Pop", "related"),
  entry("art-rock", "艺术摇滚", "Art Rock", "related"),
  entry("folk-rock", "民谣摇滚", "Folk Rock", "related"),
  entry("folk-pop", "民谣流行", "Folk Pop", "related"),
  entry("progressive-rock", "前卫摇滚", "Progressive Rock", "related"),
  entry("post-punk", "后朋克", "Post-Punk", "related"),
  entry("shoegaze", "盯鞋", "Shoegaze", "related"),
  entry("instrumental-rock", "器乐摇滚", "Instrumental Rock", "related"),
  entry("experimental-electronic", "实验电子", "Experimental Electronic", "related"),
  entry("singer-songwriter", "唱作人", "Singer-Songwriter", "related"),
  entry("indie-pop", "独立流行", "Indie Pop", "related"),
  entry("psychedelic-pop", "迷幻流行", "Psychedelic Pop", "related"),
  entry("trap", "陷阱说唱", "Trap", "related"),
  entry("jazz-rap", "爵士说唱", "Jazz Rap", "related"),
  entry("house", "浩室", "House", "related"),
  entry("synth-pop", "合成器流行", "Synth-Pop", "related"),
  entry("uk-garage", "英国车库", "UK Garage", "related"),
  entry("modern-classical", "现代古典", "Modern Classical", "related"),
  entry("modal-jazz", "调式爵士", "Modal Jazz", "related"),
  entry("spiritual-jazz", "灵性爵士", "Spiritual Jazz", "related"),
  entry("ethereal-wave", "仙音浪潮", "Ethereal Wave", "related"),
  entry("thrash-metal", "激流金属", "Thrash Metal", "related"),
  entry("soft-rock", "软摇滚", "Soft Rock", "related"),
  entry("pop-rock", "流行摇滚", "Pop Rock", "related"),
];

export const DESCRIPTOR_LABELS = {
  abstract: "抽象（Abstract）",
  acoustic: "原声（Acoustic）",
  airy: "轻盈（Airy）",
  alienated: "疏离（Alienated）",
  atmospheric: "氛围化（Atmospheric）",
  bittersweet: "苦乐参半（Bittersweet）",
  bright: "明亮（Bright）",
  calm: "平静（Calm）",
  cinematic: "电影感（Cinematic）",
  cohesive: "连贯（Cohesive）",
  confident: "自信（Confident）",
  dark: "幽暗（Dark）",
  dense: "密集（Dense）",
  digital: "数字感（Digital）",
  direct: "直接（Direct）",
  dramatic: "戏剧性（Dramatic）",
  dreamy: "梦幻（Dreamy）",
  dynamic: "动态强（Dynamic）",
  earthy: "质朴（Earthy）",
  energetic: "高能量（Energetic）",
  ethereal: "空灵（Ethereal）",
  expansive: "辽阔（Expansive）",
  explosive: "爆发力（Explosive）",
  fast: "高速（Fast）",
  futuristic: "未来感（Futuristic）",
  gradual: "渐进（Gradual）",
  groovy: "律动（Groovy）",
  hazy: "朦胧（Hazy）",
  improvised: "即兴（Improvised）",
  immersive: "沉浸（Immersive）",
  intense: "强烈（Intense）",
  intimate: "亲密（Intimate）",
  introspective: "内省（Introspective）",
  layered: "层次丰富（Layered）",
  melodic: "旋律性（Melodic）",
  melancholic: "忧郁（Melancholic）",
  meditative: "冥想（Meditative）",
  minimal: "极简（Minimal）",
  narrative: "叙事性（Narrative）",
  nocturnal: "夜行感（Nocturnal）",
  nostalgic: "怀旧（Nostalgic）",
  playful: "俏皮（Playful）",
  poetic: "诗意（Poetic）",
  polyrhythmic: "复合节奏（Polyrhythmic）",
  precise: "精密（Precise）",
  raw: "粗粝（Raw）",
  reflective: "沉思（Reflective）",
  rhythmic: "节奏鲜明（Rhythmic）",
  "sample-based": "采样驱动（Sample-Based）",
  satirical: "讽刺（Satirical）",
  sensual: "感性（Sensual）",
  spacious: "空间感（Spacious）",
  tense: "紧张（Tense）",
  textural: "音色导向（Textural）",
  theatrical: "剧场感（Theatrical）",
  traditional: "传统质感（Traditional）",
  urban: "城市感（Urban）",
  warm: "温暖（Warm）",
};

export const descriptorTaxonomy = Object.entries(DESCRIPTOR_LABELS).map(([key, label]) => ({
  key,
  label,
  kind: "descriptor",
}));
